### ISSUE TITLE
Análise de vulnerabilidade do arquivo html/socio/sistema/cadastro_cobranca_m.php

### ISSUE THREAD

**Issue by joaopontes22** [LabRedesCefetRJ/WeGIA#185]
Vulnerability Analysis
Esta aplicação apresenta duas vulnerabilidades devido a problemas no tratamento de dados de entrada:

1. **Vulnerabilidade de Injeção de SQL**: O código utiliza a função `addslashes` para lidar com possíveis aspas simples nos dados de entrada, porém essa não é uma técnica segura para prevenir ataques de injeção de SQL. Em vez disso, recomenda-se o uso de prepared statements para evitar esse tipo de vulnerabilidade.

2. **Vulnerabilidade de XSS**: O código não trata possíveis ataques de Cross Site Scripting (XSS) ao inserir diretamente os dados recebidos do usuário no banco de dados, sem realizar a devida sanitização. Para prevenir essa vulnerabilidade, é importante sanitizar e escapar os dados de entrada antes de utilizá-los em consultas SQL ou exibi-los na saída.

Além disso, há um problema de lógica no trecho de código que verifica se os dados de entrada estão vazios ou nulos. A condição `if (!isset($_POST) or empty($_POST))` não está corretamente verificando se o array `$_POST` está vazio. A verificação correta deveria ser `if (empty($_POST))`.

Por fim, há um erro na geração do valor para o campo `codigo`, onde está sendo gerado um número aleatório de forma incorreta. É recomendado corrigir essa lógica para gerar um valor aleatório válido.

É importante corrigir essas vulnerabilidades para garantir a segurança da aplicação.

**Comment by nicolly015** [comment]
- O comentário foi útil?   1 = Não útil

- Foi possível corrigir o erro?   Impossível 

Eu não achei essas vulnerabilidades importantes, mas mudei a forma de fazer a requisição com o banco de dados.

Obs: esse código também apresenta o erro 500.

**Comment by nicolly015** [comment]
### TESTE DO LADO SERVIDOR

::1 - - [03/Jul/2024:16:12:41 -0300] "GET /~dev/WeGIA/html/socio/sistema/cadastro_cobranca_m.php HTTP/1.1" 500 185 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"

==> /var/log/apache2/error.log <== 
[Wed Jul 03 16:10:55.965922 2024] [php:warn] [pid 628] [client ::1:55416] PHP Warning:  Undefined variable $socio_id in /home/dev/public_html/WeGIA/html/socio
/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:10:55.966202 2024] [php:error] [pid 628] [client ::1:55416] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL synt
ax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 in /home/dev/public_html/WeGIA/html/socio/
sistema/cadastro_cobranca_m.php:25\nStack trace:\n#0 /home/dev/public_html/WeGIA/html/socio/sistema/cadastro_cobranca_m.php(25): mysqli_prepare()\n#1 {main}\n
  thrown in /home/dev/public_html/WeGIA/html/socio/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:12:41.351210 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $socio_nome in /home/dev/public_html/WeGIA/html/so
cio/sistema/cadastro_cobranca_m.php on line 21 
[Wed Jul 03 16:12:41.351258 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $local_recepcao in /home/dev/public_html/WeGIA/htm
l/socio/sistema/cadastro_cobranca_m.php on line 22 
[Wed Jul 03 16:12:41.351281 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $forma_doacao in /home/dev/public_html/WeGIA/html/
socio/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:12:41.351301 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $receptor in /home/dev/public_html/WeGIA/html/soci
o/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:12:41.351340 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $forma_doacao in /home/dev/public_html/WeGIA/html/
socio/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:12:41.351349 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $receptor in /home/dev/public_html/WeGIA/html/soci
o/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:12:41.351358 2024] [php:warn] [pid 1499] [client ::1:57278] PHP Warning:  Undefined variable $socio_id in /home/dev/public_html/WeGIA/html/soci
o/sistema/cadastro_cobranca_m.php on line 25 
[Wed Jul 03 16:12:41.351545 2024] [php:error] [pid 1499] [client ::1:57278] PHP Fatal error:  Uncaught mysqli_sql_exception: You have an error in your SQL syn
tax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 in /home/dev/public_html/WeGIA/html/socio
/sistema/cadastro_cobranca_m.php:25\nStack trace:\n#0 /home/dev/public_html/WeGIA/html/socio/sistema/cadastro_cobranca_m.php(25): mysqli_prepare()\n#1 {main}\
n  thrown in /home/dev/public_html/WeGIA/html/socio/sistema/cadastro_cobranca_m.php on line 25

**Comment by JoaoVictorPinheiroGrandini** [comment]
Confirmado real e sério: SQL injection completo (query montada sem nenhum placeholder) e sem checagem de sessão nenhuma — qualquer visitante podia inserir cobranças arbitrárias. Corrigido para bind real + checagem de login. PR #2015.
