### ISSUE TITLE
Problema ao clicar na opção `+ informações`

### ISSUE THREAD

**Issue by GabrielPintoSouza** [LabRedesCefetRJ/WeGIA#632]
Na página `/html/socio/sistema/cobrancas.php`, quando clicamos no botão `+ informações`, a seguinte mensagem de erro é exibida no console:

`sistema.js:22 Uncaught 
TypeError: Cannot read properties of null (reading '0')
    at Object.<anonymous> (sistema.js:22:91)
    at fire (jquery-1.12.4.js:3232:31)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.js:3362:7)
    at done (jquery-1.12.4.js:9840:14)
    at XMLHttpRequest.callback (jquery-1.12.4.js:10311:8)`

**Comment by GabrielPintoSouza** [comment]
@nilsonLazarin, O erro mencionado ocorre devido a ausência de valor na coluna Cod da tabela de cobranças antigas. Isso ocorre principalmente no registro manual de novas cobranças `Novo recebimento de cobrança`. Levando em conta que essa operação é feita na tela de exibição de cobranças antigas, seria o caso de focarmos em uma correção para o problema ou removermos a opção de adicionar novas cobranças da tabela antiga, e implementarmos algo parecido na página nova (ou não implementarmos, visto que agora a página `/html/socio/sistema/psocio_geracao.php` permite a geração de boletos internamente em conjunto com os gateways de pagamento, algo que ainda não estava em funcionamento na época que esse bug foi originalmente relatado).

*OBS:* Esse bug não ocorre para as cobranças que haviam sido geradas na época que o sistema estava integrado com outra plataforma, pois a geração automática incluía um código para a cobrança.

**Comment by nilsonLazarin** [comment]
@GabrielPintoSouza 
Desative a tabela log_contribuição do script de criação do banco, pois essa função foi substituída pelo novo módulo de contribuição.
Desative as telas desse contribuição (antigo) também.
